### ISSUE TITLE
Validering - Kodeverksnavn

### ISSUE THREAD

**Issue by InsulaVentus** [I-Simen-I/kodeverk_v2.0#2]
Skal kodeverksnavn bestandig være i uppercase?
Hvilke tegn skal et navn kunne inneholde?

**Comment by I-Simen-I** [comment]
Kodeverksnavnet skal alltid ha store bokstaver
Det skal alltid starte med K_
Gyldige tegn er A-Z og _. Man kan ikke ha to understreker etter hverandre


Jeg skal oppdatere reglene på forsiden

**Comment by InsulaVentus** [comment]
Lukker jee.
