### ISSUE TITLE
Validering - Indekser kan være nullable?

### ISSUE THREAD

**Issue by InsulaVentus** [I-Simen-I/kodeverk_v2.0#5]
Skal indekser kunne være nullable? Bør i så fall kanskje vurdere å endre navn til integer, som i utgangspunktet er mer passende.

**Comment by I-Simen-I** [comment]
Jeg villle nok ha endret navnet til integer ja, hvertfall hvis vi snakker om datatypen 'i'. Men vi må også sørge for at første kolonne på hver rad har en verdi.

**Comment by InsulaVentus** [comment]
Kommer til å endre navn til integer. Kommer også til å validere på første kolonne.
